/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as ApiGenerateToolRouteImport } from './routes/api/generate/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateToolRoute = ApiGenerateToolRouteImport.update({
  id: '/api/generate/$tool',
  path: '/api/generate/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/generate/$tool': typeof ApiGenerateToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools': typeof ToolsIndexRoute
  '/api/generate/$tool': typeof ApiGenerateToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/generate/$tool': typeof ApiGenerateToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/$slug' | '/tools/' | '/api/generate/$tool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/$slug' | '/tools' | '/api/generate/$tool'
  id: '__root__' | '/' | '/tools/$slug' | '/tools/' | '/api/generate/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiGenerateToolRoute: typeof ApiGenerateToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/$tool': {
      id: '/api/generate/$tool'
      path: '/api/generate/$tool'
      fullPath: '/api/generate/$tool'
      preLoaderRoute: typeof ApiGenerateToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiGenerateToolRoute: ApiGenerateToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
